apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sahab2-cluster-admin
subjects:
  {{- range $user := .Values.clusteradmin.users }}
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: {{ $user }}
  {{- end }}
  {{- range $group := .Values.clusteradmin.groups }}
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ $group }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin