apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sahab2-view
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: https://canpolattest.uaenorth.cloudapp.azure.com/auth/realms/master#2d3b8f9c-2864-43a1-8fee-daaa7a21e309
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view